=== chrislit/versification/canon.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="ST_abbr">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="id">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="collection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="book" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="book">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="id"/>
				<xs:element ref="abbr" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="name" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="abbr">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_abbr">
					<xs:attribute name="mode">
						<xs:simpleType>
							<xs:restriction base="xs:string"/>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== chrislit/versification/canon.qumran.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="canon.xsd">
<!-- Collection name: qumran -->


	<!-- Qumran Scrolls -->

	<book>
		<id>1QGen</id>
		<name>1Q1</name>
	</book>
	<book>
		<id>1QEx</id>
		<name>1Q2</name>
	</book>
	<book>
		<id>1QpaleoLev</id>
		<name>1Q3</name>
	</book>
	<book>
		<id>1QDeuta</id>
		<name>1Q4</name>
	</book>
	<book>
		<id>1QDeutb</id>
		<name>1Q5</name>
	</book>
	<book>
		<id>1QJudg</id>
		<name>1Q6</name>
	</book>
	<book>
		<id>1QSam</id>
		<name>1Q7</name>
	</book>
	<book>
		<id>1QIsab</id>
		<name>1Q8</name>
	</book>
	<book>
		<id>1QEzek</id>
		<name>1Q9</name>
	</book>
	<book>
		<id>1QPsa</id>
		<name>1Q10</name>
	</book>
	<book>
		<id>1QPsb</id>
		<name>1Q11</name>
	</book>
	<book>
		<id>1QPsc</id>
		<name>1Q12</name>
	</book>
	<book>
		<id>1Qphyl</id>
		<name>1Q13</name>
	</book>
	<book>
		<id>1QpMic</id>
		<name>1Q14</name>
	</book>
	<book>
		<id>1QpZeph</id>
		<name>1Q15</name>
	</book>
	<book>
		<id>1QpPs</id>
		<name>1Q16</name>
	</book>
	<book>
		<id>1QJuba</id>
		<name>1Q17</name>
	</book>
	<book>
		<id>1QJubb</id>
		<name>1Q18</name>
	</book>
	<book>
		<id>1QNoah</id>
		<name>1Q19</name>
		<name>1Q19bis</name>
	</book>
	<book>
		<id>1QapGen</id>
		<name>1Q20</name>
	</book>
	<book>
		<id>1QTLeviar</id>
		<name>1Q21</name>
	</book>
	<book>
		<id>1QDM</id>
		<name>1Q22</name>
	</book>
	<book>
		<id>1QEnGiants</id>
		<name>1Q23</name>
		<name>1Q24</name>
	</book>
	<book>
		<id>1QMyst</id>
		<name>1Q27</name>
	</book>
	<book>
		<id>1QSa</id>
		<name>1Q28a</name>
	</book>
	<book>
		<id>1QSb</id>
		<name>1Q28b</name>
	</book>
	<book>
		<id>1QJNar</id>
		<name>1Q32</name>
	</book>
	<book>
		<id>1QMfrs</id>
		<name>1Q33</name>
	</book>
	<book>
		<id>1QLitPra</id>
		<name>1Q34</name>
	</book>
	<book>
		<id>1QLitPrb</id>
		<name>1Q34bis</name>
	</book>
	<book>
		<id>1QHfrs</id>
		<name>1Q35</name>
	</book>
	<book>
		<id>1QDana</id>
		<name>1Q71</name>
	</book>
	<book>
		<id>1QDanb</id>
		<name>1Q72</name>
	</book>

</collection>

=== chrislit/versification/canon.naghammadi.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="canon.xsd">
<!-- Collection name: naghammadi -->


	<!-- Nag Hammadi -->

	<book>
		<id>ActsPet12Apost</id>
		<name>Acts of Peter and the Twelve Apostles</name>
	</book>
	<book>
		<id>Allogenes</id>
		<name>Allogenes</name>
	</book>
	<book>
		<id>ApocJas</id>
		<name>Apocryphon of James</name>
	</book>
	<book>
		<id>ApocJn</id>
		<name>Apocryphon of John</name>
	</book>
	<book>
		<id>ApAdam</id>
		<name>Apocalypse of Adam</name>
	</book>
	<book>
		<id>1ApJas</id>
		<name>I Apocalypse of James</name>
		<name>IApocalypse of James</name>
		<name>1 Apocalypse of James</name>
		<name>1Apocalypse of James</name>
	</book>
	<book>
		<id>2ApJas</id>
		<name>II Apocalypse of James</name>
		<name>IIApocalypse of James</name>
		<name>2 Apocalypse of James</name>
		<name>2Apocalypse of James</name>
	</book>
	<book>
		<id>ApPaul</id>
		<name>Apocalypse of Paul</name>
	</book>
	<book>
		<id>ApPet</id>
		<name>Apocalypse of Peter</name>
	</book>
	<book>
		<id>Asclepius</id>
		<name>Asclepius</name>
	</book>
	<book>
		<id>AuthTeach</id>
		<name>Authoritative Teaching</name>
	</book>
	<book>
		<id>DialSav</id>
		<name>Dialogue of the Savior</name>
	</book>
	<book>
		<id>Disc89</id>
		<abbr>Disc8-9</abbr>
		<name>Discourse on the Eighth and Ninth</name>
	</book>
	<book>
		<id>EpPetPhil</id>
		<name>Letter of Peter to Philip</name>
	</book>
	<book>
		<id>Eugnostos</id>
		<name>Eugnostos the Blessed</name>
	</book>
	<book>
		<id>ExegSoul</id>
		<name>Exegesis on the Soul</name>
	</book>
	<book>
		<id>GEgyp</id>
		<name>Gospel of the Egyptians</name>
	</book>
	<book>
		<id>GPhil</id>
		<name>Gospel of Philip</name>
	</book>
	<book>
		<id>GThom</id>
		<name>Gospel of Thomas</name>
	</book>
	<book>
		<id>GreatPow</id>
		<name>The Concept of Our Great Power</name>
	</book>
	<book>
		<id>HypArch</id>
		<name>Hypostasis of the Archons</name>
	</book>
	<book>
		<id>Hypsiph</id>
		<name>Hypsiphrone</name>
	</book>
	<book>
		<id>InterpKnow</id>
		<name>Interpretation of Knowledge</name>
	</book>
	<book>
		<id>Marsanes</id>
		<name>Marsanes</name>
	</book>
	<book>
		<id>Melch</id>
		<name>Melchizedek</name>
	</book>
	<book>
		<id>Norea</id>
		<name>Thought of Norea</name>
	</book>
	<book>
		<id>OnBapA</id>
		<name>On the Baptism A</name>
	</book>
	<book>
		<id>OnBapB</id>
		<name>On the Baptism B</name>
	</book>
	<book>
		<id>OnEuchA</id>
		<name>On the Eucharist A</name>
	</book>
	<book>
		<id>OnEuchB</id>
		<name>On the Eucharist B</name>
	</book>
	<book>
		<id>OrigWorld</id>
		<name>On the Origin of the World</name>
	</book>
	<book>
		<id>ParaphShem</id>
		<name>Paraphrase of Shem</name>
	</book>
	<book>
		<id>PrPaul</id>
		<name>Prayer of the Apostle Paul</name>
	</book>
	<book>
		<id>PrThanks</id>
		<name>Prayer of Thanksgiving</name>
	</book>
	<book>
		<id>SentSextus</id>
		<name>Sentences of Sextus</name>
	</book>
	<book>
		<id>SophJesChr</id>
		<name>Sophia of Jesus Christ</name>
	</book>
	<book>
		<id>StelesSeth</id>
		<name>Three Steles of Seth</name>
	</book>
	<book>
		<id>TeachSilv</id>
		<name>Teachings of Silvanus</name>
	</book>
	<book>
		<id>TestimTruth</id>
		<name>Testimony of Truth</name>
	</book>
	<book>
		<id>ThomCont</id>
		<name>Book of Thomas the Contender</name>
	</book>
	<book>
		<id>Thund</id>
		<name>The Thunder: Perfect Mind</name>
	</book>
	<book>
		<id>TreatRes</id>
		<name>Treatise on the Resurrection</name>
	</book>
	<book>
		<id>TreatSeth</id>
		<name>Second Treatise of the Great Seth</name>
	</book>
	<book>
		<id>TriTrac</id>
		<name>Tripartite Tractate</name>
	</book>
	<book>
		<id>TrimProt</id>
		<name>Trimorphic Protennoia</name>
	</book>
	<book>
		<id>ValExp</id>
		<name>A Valentinian Exposition</name>
	</book>
	<book>
		<id>Zost</id>
		<name>Zostrianos</name>
	</book>

	<!-- Not listed in SBL -->

	<book>
		<id>PlatoRep</id>
		<name>Plato Republic 588A-589B</name>
	</book>
	<book>
		<id>ScribalNote</id>
		<name>Scribal Note</name>
	</book>
	<book>
		<id>OnAnoint</id>
		<name>On the Anointing</name>
		<name>On the Baptism C(??)</name>
	</book>
	<book>
		<id>Frm</id>
		<name>Fragments</name>
	</book>

</collection>

=== chrislit/versification/canon.classical.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="canon.xsd">
<!-- Collection name: classical -->


	<!-- Josephus -->

	<book>
		<id>Ant</id>
		<name>Jewish Antiquities</name>
	</book>
	<book>
		<id>Apion</id>
		<name>Against Apion</name>
	</book>
	<book>
		<id>Life</id>
		<name>Life of Josephus</name>
	</book>
	<book>
		<id>War</id>
		<name>Jewish Wars</name>
	</book>

</collection>

=== chrislit/versification/canon.otp.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="canon.xsd">
<!-- Collection name: otp -->

	<!-- OT Pseudepigrapha -->

	<book>
		<id>ApAb</id>
		<name>Apocalypse of Abraham</name>
	</book>
	<book>
		<id>TAb</id>
		<name>Testament of Abraham</name>
	</book>
	<book>
		<id>ApAdam</id>
		<name>Apocalypse of Adam</name>
	</book>
	<book>
		<id>TAdam</id>
		<name>Testament of Adam</name>
	</book>
	<book>
		<id>LAE</id>
		<abbr>Ada</abbr>
		<name>Life of Adam and Eve</name>
	</book>
	<book>
		<id>Ah</id>
		<name>Ahiqar</name>
	</book>
	<book>
		<id>AnonSam</id>
		<name>An Anonymous Samaritan Text</name>
	</book>
	<book>
		<id>LetAris</id>
		<name>Letter of Aristeas</name>
	</book>
	<book>
		<id>ArisEx</id>
		<name>Aristeas the Exegete</name>
	</book>
	<book>
		<id>Aristob</id>
		<name>Aristobolus</name>
	</book>
	<book>
		<id>Art</id>
		<name>Artapanus</name>
	</book>
	<book>
		<id>3Bar</id>
		<abbr>3Ba</abbr>
		<name>III Baruch</name>
		<name>IIIBaruch</name>
		<name>3 Baruch</name>
		<name>3Baruch</name>
		<name>Greek Apocalypse of Baruch</name>
	</book>
	<book>
		<id>CavTr</id>
		<name>Cave of Treasures</name>
	</book>
	<book>
		<id>ClMal</id>
		<name>Cleodemus Malchus</name>
	</book>
	<book>
		<id>ApDan</id>
		<name>Apocalypse of Daniel</name>
	</book>
	<book>
		<id>Dem</id>
		<name>Demetrius</name>
	</book>
	<book>
		<id>ElMod</id>
		<name>Eldad and Modad</name>
	</book>
	<book>
		<id>ApEl</id>
		<name>Apocalypse of Elijah</name>
	</book>
	<book>
		<id>HebApEl</id>
		<name>Hebrew Apocalypse of Elijah</name>
	</book>
	<book>
		<id>2En</id>
		<name>II Enoch</name>
		<name>IIEnoch</name>
		<name>2 Enoch</name>
		<name>2Enoch</name>
		<name>Slavonic Apocalypse of Enoch</name>
	</book>
	<book>
		<id>3En</id>
		<name>III Enoch</name>
		<name>IIIEnoch</name>
		<name>3 Enoch</name>
		<name>3Enoch</name>
		<name>Hebrew Apocalypse of Enoch</name>
	</book>
	<book>
		<id>Eup</id>
		<name>Eupolemus</name>
	</book>
	<book>
		<id>PsEup</id>
		<abbr>Ps-Eup</abbr>
		<name>Pseudo-Eupolemus</name>
	</book>
	<book>
		<id>ApocEzek</id>
		<name>Apocryphon of Ezekiel</name>
	</book>
	<book>
		<id>ApEzek</id>
		<name>Apocalypse of Ezekiel</name>
	</book>
	<book>
		<id>EzekTrag</id>
		<name>Ezekiel the Tragedian</name>
	</book>
	<book>
		<id>GkApEzra</id>
		<name>Greek Apocalypse of Ezra</name>
	</book>
	<book>
		<id>QuesEzra</id>
		<name>Questions of Ezra</name>
	</book>
	<book>
		<id>RevEzra</id>
		<name>Revelation of Ezra</name>
	</book>
	<book>
		<id>VisEzra</id>
		<name>Vision of Ezra</name>
	</book>
	<book>
		<id>HecAb</id>
		<name>Hecataeus Abdera</name>
	</book>
	<book>
		<id>PsHec</id>
		<abbr>Ps-Hec</abbr>
		<name>Pseudo-Hecataeus</name>
	</book>
	<book>
		<id>HelSynPr</id>
		<name>Hellenistic Synagogal Prayers</name>
	</book>
	<book>
		<id>THez</id>
		<name>Testament of Hezekiah</name>
	</book>
	<book>
		<id>FrgsHistWrks</id>
		<name>Fragments of Historical Works</name>
	</book>
	<book>
		<id>TIsaac</id>
		<name>Testament of Isaac</name>
	</book>
	<book>
		<id>AscenIs</id>
		<name>Ascension of Isaiah</name>
	</book>
	<book>
		<id>MartIs</id>
		<abbr>MrI</abbr>
		<name>Martyrdom of Isaiah</name>
	</book>
	<book>
		<id>VisIs</id>
		<name>Vision of Isaiah</name>
	</book>
	<book>
		<id>LadJac</id>
		<name>Ladder of Jacob</name>
	</book>
	<book>
		<id>PrJac</id>
		<name>Prayer of Jacob</name>
	</book>
	<book>
		<id>TJac</id>
		<name>Testament of Jacob</name>
	</book>
	<book>
		<id>JanJam</id>
		<name>Jannes and Jambres</name>
	</book>
	<book>
		<id>TJob</id>
		<name>Testament of Job</name>
	</book>
	<book>
		<id>JosAsen</id>
		<name>Joseph and Aseneth</name>
	</book>
	<book>
		<id>HistJos</id>
		<name>History of Joseph</name>
	</book>
	<book>
		<id>PrJos</id>
		<name>Prayer of Joseph</name>
	</book>
	<book>
		<id>LAB</id>
		<name>Liber Antiquitatum Biblicarum</name>
	</book>
	<book>
		<id>LosTr</id>
		<name>The Lost Tribes</name>
	</book>
	<book>
		<id>5Mac</id>
		<abbr>5Ma</abbr>
		<name>V Maccabees</name>
		<name>5 Maccabees</name>
		<name>5Maccabees</name>
	</book>
	<book>
		<id>SyrMen</id>
		<name>Syriac Menander</name>
	</book>
	<book>
		<id>ApMos</id>
		<name>Apocalypse of Moses</name>
	</book>
	<book>
		<id>AsMos</id>
		<abbr>AsM</abbr>
		<name>Assumption of Moses</name>
	</book>
	<book>
		<id>PrMos</id>
		<name>Prayer of Moses</name>
	</book>
	<book>
		<id>TMos</id>
		<name>Testament of Moses</name>
	</book>
	<book>
		<id>BkNoah</id>
		<name>Book of Noah</name>
	</book>
	<book>
		<id>PsOrph</id>
		<abbr>Ps-Orph</abbr>
		<name>Orphica</name>
		<name>Pseudo-Orpheus</name>
	</book>
	<book>
		<id>PhEPoet</id>
		<name>Philo the Epic Poet</name>
	</book>
	<book>
		<id>PsPhilo</id>
		<abbr>Ps-Philo</abbr>
		<name>Pseudo-Philo</name>
	</book>
	<book>
		<id>PsPhoc</id>
		<abbr>Ps-Phoc</abbr>
		<name>Pseudo-Phocyclides</name>
	</book>
	<book>
		<id>FrgsPoetWrks</id>
		<name>Fragments of Poetic Works</name>
	</book>
	<book>
		<id>LivPro</id>
		<name>Lives of the Prophets</name>
	</book>
	<book>
		<id>HistRech</id>
		<name>History of the Rechabites</name>
	</book>
	<book>
		<id>ApSedr</id>
		<name>Apocalypse of Sedrach</name>
	</book>
	<book>
		<id>TrShem</id>
		<name>Treatise of Shem</name>
	</book>
	<book>
		<id>SibOr</id>
		<abbr>Sib</abbr>
		<name>Sibylline Oracles</name>
	</book>
	<book>
		<id>TSol</id>
		<name>Testament of Solomon</name>
	</book>
	<book>
		<id>Thal</id>
		<name>Thallus</name>
	</book>
	<book>
		<id>Theod</id>
		<name>Theodotus</name>
	</book>
	<book>
		<id>T12P</id>
		<name>Testaments of the Twelve Patriarchs</name>
	</book>
	<book>
		<id>TReu</id>
		<abbr>12R</abbr>
		<name>Testament of Reuben</name>
	</book>
	<book>
		<id>TSim</id>
		<abbr>12S</abbr>
		<name>Testament of Simeon</name>
	</book>
	<book>
		<id>TLevi</id>
		<abbr>12L</abbr>
		<name>Testament of Levi</name>
	</book>
	<book>
		<id>TJud</id>
		<abbr>12J</abbr>
		<name>Testament of Judah</name>
	</book>
	<book>
		<id>TIss</id>
		<abbr>12I</abbr>
		<name>Testament of Issachar</name>
	</book>
	<book>
		<id>TZeb</id>
		<abbr>12Z</abbr>
		<name>Testament of Zebulon</name>
	</book>
	<book>
		<id>TDan</id>
		<abbr>12D</abbr>
		<name>Testament of Dan</name>
	</book>
	<book>
		<id>TNaph</id>
		<abbr>12N</abbr>
		<name>Testament of Naphtali</name>
	</book>
	<book>
		<id>TGad</id>
		<abbr>12G</abbr>
		<name>Testament of Gad</name>
	</book>
	<book>
		<id>TAsh</id>
		<abbr>12A</abbr>
		<name>Testament of Asher</name>
	</book>
	<book>
		<id>TJos</id>
		<abbr>12O</abbr>
		<name>Testament of Joseph</name>
	</book>
	<book>
		<id>TBenj</id>
		<abbr>12B</abbr>
		<name>Testament of Benjamin</name>
	</book>
	<book>
		<id>Vita</id>
		<name>Vita Adae et Evae</name>
	</book>
	<book>
		<id>ApZeph</id>
		<name>Apocalypse of Zephaniah</name>
	</book>
	<book>
		<id>ApZos</id>
		<name>Apocalypse of Zosimus</name>
	</book>

	<!-- Not listed in SBL -->

	<book>
		<id>T3P</id>
		<name>Testaments of the Three Patriarchs</name>
	</book>
	<book>
		<id>VisDan</id>
		<name>Vision of Daniel</name>
	</book>
	<book>
		<id>DeathAb</id>
		<name>Death of Abraham</name>
	</book>
	<book>
		<id>Jash</id>
		<name>Book of Jasher</name>
	</book>
	<book>
		<id>ConfAES</id>
		<name>Conflict of Adam and Eve with Satan</name>
	</book>
	<book>
		<id>Rolls</id>
		<name>Book of the Rolls</name>
	</book>
	<book>
		<id>SinSol</id>
		<name>Sin of Solomon</name>
	</book>
	<book>
		<id>SyrApEzra</id>
		<name>Syriac Apocalypse of Ezra</name>
	</book>
	<book>
		<id>Bee</id>
		<name>Book of the Bee</name>
	</book>
	<book>
		<id>QuesQueen</id>
		<name>Questions Addressed by the Queen (of Sheeba) and Answers Given by Solomon</name>
	</book>
	<book>
		<id>1AdamEve</id>
		<name>I Adam and Eve</name>
		<name>IAdam and Eve</name>
		<name>1 Adam and Eve</name>
		<name>1Adam and Eve</name>
	</book>
	<book>
		<id>2AdamEve</id>
		<name>II Adam and Eve</name>
		<name>IIAdam and Eve</name>
		<name>2 Adam and Eve</name>
		<name>2Adam and Eve</name>
	</book>

</collection>

=== chrislit/versification/canon.af.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="canon.xsd">
<!-- Collection name: af -->

	<!-- Apostolic Fathers -->
	<book>
		<id>Barn</id>
		<abbr>Brn</abbr>
		<abbr mode="olb">Bar</abbr>
		<name>Barnabas</name>
	</book>
	<book>
		<id>1Clem</id>
		<abbr>1Cl</abbr>
		<name>I Clement</name>
		<name>IClement</name>
		<name>1 Clement</name>
		<name>1Clement</name>
	</book>
	<book>
		<id>2Clem</id>
		<abbr>2Cl</abbr>
		<name>II Clement</name>
		<name>IIClement</name>
		<name>2 Clement</name>
		<name>2Clement</name>
	</book>
	<book>
		<id>Did</id>
		<name>Didache</name>
	</book>
	<book>
		<id>Diogn</id>
		<abbr>Dio</abbr>
		<name>Diognetus</name>
	</book>
	<book>
		<id>Herm</id>
		<name>Shepherd of Hermas</name>
	</book>
	<book>
		<id>HermMan</id>
		<abbr>Com</abbr>
		<abbr>HCo</abbr>
		<name>Hermas: Mandates</name>
	</book>
	<book>
		<id>HermSim</id>
		<abbr>Sim</abbr>
		<abbr>HSm</abbr>
		<name>Hermas: Similitudes</name>
	</book>
	<book>
		<id>HermVis</id>
		<abbr>Vis</abbr>
		<abbr>HVs</abbr>
		<name>Hermas: Visions</name>
	</book>
	<book>
		<id>IgnMagn</id>
		<abbr>IMg</abbr>
		<abbr>Mag</abbr>
		<name>Ignatius to the Magnesians</name>
	</book>
	<book>
		<id>IgnPhld</id>
		<abbr>IPh</abbr>
		<abbr mode="olb">Phi</abbr>
		<name>Ignatius to the Philadephians</name>
	</book>
	<book>
		<id>IgnPol</id>
		<abbr>IPo</abbr>
		<abbr mode="olb">Pol</abbr>
		<name>Ignatius to Polycarp</name>
	</book>
	<book>
		<id>IgnRom</id>
		<abbr>IRo</abbr>
		<abbr mode="olb">Rom</abbr>
		<name>Ignatius to the Romans</name>
	</book>
	<book>
		<id>IgnSmyrn</id>
		<abbr>ISm</abbr>
		<abbr>Smy</abbr>
		<name>Ignatius to the Smyrnaeans</name>
	</book>
	<book>
		<id>IgnTrall</id>
		<abbr>ITr</abbr>
		<abbr>Tra</abbr>
		<name>Ignatius to the Trallians</name>
	</book>
	<book>
		<id>IgnEph</id>
		<abbr>IEp</abbr>
		<!-- used by OLB, but overlaps with Ephesians abbrev <abbr mode="olb">Eph</abbr> -->
		<name>Ignatius to the Ephesians</name>
	</book>
	<book>
		<id>MartPol</id>
		<abbr>MPo</abbr>
		<name>Martyrdom of Polycarp</name>
	</book>
	<book>
	        <id>PolPhil</id>
		<abbr>Pol</abbr>
		<!-- used by OLB, but overlaps with Philippians abbrev <abbr mode="olb">Php</abbr> -->
		<name>Polycarp to the Philippians</name>
	</book>
	<book>
	        <id>AposCreed</id>
		<abbr mode="bw">Apc</abbr>
		<name>Apostles' Creed</name>
	</book>
	<book>
	        <id>Pap</id>
		<name>Fragments of Papias</name>
	</book>

	<!-- long versions -->

	<book>
		<id>IgnMagnLg</id>
		<abbr>IMl</abbr>
		<name>Ignatius to the Magnesians (Longer)</name>
	</book>
	<book>
		<id>IgnPhldLg</id>
		<abbr>IPl</abbr>
		<name>Ignatius to the Philadephians (Longer)</name>
	</book>
	<book>
		<id>IgnPolLg</id>
		<abbr>IPc</abbr>
		<name>Ignatius to Polycarp (Longer)</name>
	</book>
	<book>
		<id>IgnRomLg</id>
		<abbr>IRl</abbr>
		<name>Ignatius to the Romans (Longer)</name>
	</book>
	<book>
		<id>IgnSmyrnLg</id>
		<abbr>ISl</abbr>
		<name>Ignatius to the Smyrnaeans (Longer)</name>
	</book>
	<book>
		<id>IgnTrallLg</id>
		<abbr>ITl</abbr>
		<name>Ignatius to the Trallians (Longer)</name>
	</book>
	<book>
		<id>IgnEphLg</id>
		<abbr>IEl</abbr>
		<name>Ignatius to the Ephesians (Longer)</name>
	</book>

</collection>

=== chrislit/versification/canon.lds.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="canon.xsd">
<!-- Collection name: lds -->


	<!-- Book of Mormon -->

	<book>
		<id>1Ne</id>
		<name>I Nephi</name>
		<name>INephi</name>
		<name>1 Nephi</name>
		<name>1Nephi</name>
	</book>
	<book>
		<id>2Ne</id>
		<name>II Nephi</name>
		<name>IINephi</name>
		<name>2 Nephi</name>
		<name>2Nephi</name>
	</book>
	<book>
		<id>Jacob</id>
		<name>Jacob</name>
	</book>
	<book>
		<id>Enos</id>
		<name>Enos</name>
	</book>
	<book>
		<id>Jarom</id>
		<name>Jarom</name>
	</book>
	<book>
		<id>Omni</id>
		<name>Omni</name>
	</book>
	<book>
		<id>WofM</id>
		<name>Words of Mormon</name>
	</book>
	<book>
		<id>Mosiah</id>
		<name>Mosiah</name>
	</book>
	<book>
		<id>Alma</id>
		<name>Alma</name>
	</book>
	<book>
		<id>Hel</id>
		<name>Helaman</name>
	</book>
	<book>
		<id>3Ne</id>
		<name>III Nephi</name>
		<name>IIINephi</name>
		<name>3 Nephi</name>
		<name>3Nephi</name>
	</book>
	<book>
		<id>4Ne</id>
		<name>IV Nephi</name>
		<name>IVNephi</name>
		<name>4 Nephi</name>
		<name>4Nephi</name>
	</book>
	<book>
		<id>Morm</id>
		<name>Mormon</name>
	</book>
	<book>
		<id>Ether</id>
		<name>Ether</name>
	</book>
	<book>
		<id>Moro</id>
		<name>Moroni</name>
	</book>

	<!-- Pearl of Great Price -->

	<book>
		<id>Moses</id>
		<name>Book of Moses</name>
	</book>
	<book>
		<id>Abr</id>
		<name>Book of Abraham</name>
	</book>
	<book>
		<id>JSM</id>
		<abbr>JS-M</abbr>
		<name>Joseph Smith-Matthew</name>
	</book>
	<book>
		<id>JSH</id>
		<abbr>JS-H</abbr>
		<name>Joseph Smith-History</name>
	</book>
	<book>
		<id>AofF</id>
		<name>Articles of Faith</name>
	</book>

	<!-- Doctrine & Covenants -->

	<book>
		<id>DC</id>
		<abbr>D&amp;C</abbr>
		<name>Doctrine and Covenants</name>
		<name>Doctrine &amp; Covenants</name>
	</book>
	<book>
		<id>OD</id>
		<name>Official Declaration</name>
	</book>

</collection>
